[versions]
androidGradlePlugin = "8.13.1"
moshi="1.15.2"
kotlin = "2.2.21"
kotlinxSerialization = "2.2.21"
ksp="2.3.3"
coroutines = "1.10.2"
androidDesugarJdkLibs = "2.1.5"
androidXCore = "1.17.0"
androidXCompat = "1.7.1"
androidxComposeBom = "2025.12.00"
androidxActivity = "1.12.0"
constraintlayout = "2.2.1"
constraintlayoutCompose="1.1.1"
accompanist = "0.36.0"
composeNavigation = "2.9.6"
composeLifecycle = "2.10.0"
androidx-compose-material3 = "1.4.0"
androidx-compose-material3-adaptive = "1.2.0"
dagger="2.57.2"
hilt="1.3.0"
androidxHiltNavigationCompose="1.3.0"
junit = "6.0.1"
espresso = "3.5.1"
mockito = "5.20.0"
mockito_inline = "5.2.0"
mockito_kotlin = "6.1.0"
truth = "1.4.5"
turbine = "1.2.1"
retrofit = "3.0.0"
okhttp = "5.3.2"
detekt = "1.23.8"
versionsPlugin = "0.53.0"
leakCanary = "2.14"
lint = "31.0.0"
material = "1.13.0"
navigation = "2.9.6"
workManager = "2.11.0"
datastore = "1.2.0"
googleServicesPlugin="4.4.4"
firebaseBom="34.7.0"
crashlyticsPlugin="3.0.6"
room = "2.8.4"
androidXglance = "1.1.1"
chucker="4.2.0"
flipper="0.273.0"
soloader="0.12.1"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
kotlinSerialization = "2.1.21"
kotlinxSerializationCore = "1.8.1"
material3AdaptiveNav3 = "1.3.0-alpha04"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidXCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }
android-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXCompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class" }

androidx-compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "androidx-compose-material3-adaptive" }
androidx-compose-material3-adaptive-navigationSuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "androidx-compose-material3" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }

androidx-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito_inline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito_kotlin" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt"}
leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }
material = { group = "com.google.android.material", name = "material", version.ref = "material"}
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation"}
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation"}
work-manager-runtime = { group = "androidx.work", name="work-runtime", version.ref = "workManager"}
datastore = { group = "androidx.datastore", name="datastore", version.ref = "datastore"}
datastore-preferences = { group = "androidx.datastore", name="datastore-preferences", version.ref = "datastore"}
datastore-core = { group = "androidx.datastore", name="datastore-core", version.ref = "datastore" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
room-compiler = { group ="androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group ="androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group ="androidx.room", name = "room-ktx", version.ref = "room" }
androidx-glance-appwidget = { group ="androidx.glance", name = "glance-appwidget", version.ref = "androidXglance" }
androidx-glance-material3 = { group ="androidx.glance", name = "glance-material3", version.ref = "androidXglance" }
chucker = { group ="com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-noop = { group ="com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }
flipper = { group ="com.facebook.flipper", name = "flipper", version.ref = "flipper" }
flipper-plugin-network = { group ="com.facebook.flipper", name = "flipper-network-plugin", version.ref = "flipper" }
soloader = { group ="com.facebook.soloader", name = "soloader", version.ref = "soloader" }
flipper-noop = { group ="com.facebook.flipper", name = "flipper-noop", version.ref = "flipper" }
flipper-plugins-noop = { group ="com.github.theGlenn", name = "flipper-android-no-op", version = "0.11.4" }
kotlinx-serialization-json = { group ="org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }

[bundles]
ui = ["androidx-core", "androidx-core-ktx", "android-compat", "androidx-constraintlayout"]
old-ui = ["material", "navigation-fragment", "navigation-ui"]
compose-ui = ["androidx-compose-ui", "androidx-compose-animation", "androidx-compose-foundation", "androidx-compose-material3", "androidx-compose-material3-window", "androidx-accompanist-systemuicontroller", "androidx-compose-ui-tooling", "androidx-compose-ui-tooling-preview", "androidx-navigation-compose", "androidx-lifecycle-compose", "androidx-lifecycle-runtime-compose", "androidx-constraintlayout-compose", "androidx-compose-material", "androidx-compose-material3-adaptive-navigation", "androidx-compose-material3-adaptive-layout", "androidx-compose-material3-adaptive", "androidx-compose-material3-adaptive-navigationSuite", "androidx-compose-material-iconsExtended", "androidx-material-icons-core"]
test = ["coroutines-test", "junit-api", "junit-params", "mockito-core", "mockito-inline", "mockito-kotlin", "truth", "turbine"]
network = ["moshi-adapters", "okhttp", "okhttp-logging", "retrofit", "retrofit-moshi"]
debug =  ["leak-canary"]
work-manager = ["work-manager-runtime"]
hilt = ["dagger-hilt-android", "hilt-common", "hilt-work"]
datastore = ["datastore", "datastore-preferences", "datastore-core"]
firebase = ["firebase-crashlytics"]
androidx-glance = ["androidx-glance-appwidget", "androidx-glance-material3"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin"}
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin"}
room = { id = "androidx.room", version.ref = "room" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization" }
